name: deploy to lambda
on:
  workflow_run:
    workflows: [unitest]
    types:
      - completed
jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v3
#      - name: zip
#        uses: montudor/action-zip@v0.1.0
#        with:
#          args: zip -qq -r ./bundle.zip ./src/Function
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{  secrets.AWS_REGION  }}
          function_name: visitorLambdaFunction
#          zip_file: bundle.zip
          source: ./src/Function
