name: sam deploy
on:
  push:
    branches:
      - master
jobs:
  build-deploy-sam:
    name: Build and Deploy SAM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:  set up Python3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}
      # sam build
      - run: sam build --use-container

      # Run Unit tests- Specify unit tests here

      # sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name dev --s3-bucket aws-cli-managed-challenge --capabilities CAPABILITY_IAM --region us-east-1
  test-lambda-function:
    needs: build-deploy-sam
    name:  Unitest lambda function
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install flake8 pytest
          pip install -r src/Function/requirements.txt
      - name: Test with pytest
        run: |
          pytest
  deploy-lambda-function:
    needs: test-lambda-function
    name: Deploy Lambda function
    steps:
      deploy_source:
        name: build and deploy lambda
        runs-on: ubuntu-latest
        steps:
          - name: default deploy
            uses: appleboy/lambda-action@master
            with:
              aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws_region: ${{  secrets.AWS_REGION  }}
              function_name: visitorLambdaFunction
              source: ./src/Function/handler.py